ERROR:root:
Traceback (most recent call last):
  File "f:\WebScraping\mahmud.py", line 4, in <module>
    raise Exception
Exception
